name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      ID: ${{ dockerhub.DOCKERID }}
      SECRET: ${{dockerhub.DOCKERPWD}}
      IMAGE : "angular-basics-2021"
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Software Build "npm | docker"
      run: |
        npm install
        npm run build --if-present
        docker build . --file dockerfile --tag jalalhejazi/angular-basics-2021:latest
        docker login -u ${{env.ID}} -p ${{env.SECRET}}
        docker push jalalhejazi/angular-basics-2021
    
