name: Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      ID: ${{secrets.DOCKERID}}
      SECRET: ${{secrets.DOCKERPASSWORD}}
      IMAGE : "jalalhejazi/angular-automation-2022"
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
       username: ${{env.ID}}
       password: ${{env.SECRET}}
    
    - name: Software Build "npm | docker"
      run: |
        npm install --silent
        npm run build --if-present
        docker build . --file dockerfile --tag ${{env.IMAGE}}:latest
        docker push ${{env.IMAGE}}
